### ISSUE TITLE
Parser chokes on some types

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-java-parser#17]
Latest code generation chokes on some mis-handled types. The goal of this task is to regenerate all codes for ruby and verify it works:
* Ruby client -- see [gen_config instructions](https://github.com/killbill/killbill-client-ruby/blob/master/gen_config/model.conf)
* APIs 
  * Kill Bill Plugin apis -- see  [gen_config instructions](https://github.com/killbill/killbill-plugin-framework-ruby/blob/master/gen_config/plugin_api.conf)
  * Kill Bill apis -- see  [gen_config instructions](https://github.com/killbill/killbill-plugin-framework-ruby/blob/master/gen_config/api.conf)

Example:
```
Exception in thread "main" com.ning.killbill.generators.GeneratorException: Cannot find classEnumOrInterface java.io.File
	at com.ning.killbill.generators.BaseGenerator.findClassEnumOrInterface(BaseGenerator.java:67)
	at com.ning.killbill.generators.ruby.JRubyPluginGenerator.writeConversionToJava(JRubyPluginGenerator.java:688)
	at com.ning.killbill.generators.ruby.JRubyPluginGenerator.writeConversionToJava(JRubyPluginGenerator.java:573)
	at com.ning.killbill.generators.ruby.JRubyPluginGenerator.writeConversionToJava(JRubyPluginGenerator.java:565)
	at com.ning.killbill.generators.ruby.JRubyPluginGenerator.generateToJava(JRubyPluginGenerator.java:531)
	at com.ning.killbill.generators.ruby.JRubyPluginGenerator.generateForPojo(JRubyPluginGenerator.java:357)
	at com.ning.killbill.generators.ruby.JRubyPluginGenerator.generateClass(JRubyPluginGenerator.java:144)
	at com.ning.killbill.generators.ClientLibraryBaseGenerator.generate(ClientLibraryBaseGenerator.java:65)
	at com.ning.killbill.generators.DistpatchGenerator.generate(DistpatchGenerator.java:33)
	at com.ning.killbill.KillbillParser.main(KillbillParser.java:50)
```

**Comment by pierre** [comment]
Similar issue with latest Catalog objects:

```
[main] INFO com.ning.killbill.generators.ClientLibraryBaseGenerator - Generating file for object Unit
[main] INFO com.ning.killbill.generators.ClientLibraryBaseGenerator - Generating file for object Usage
[main] INFO com.ning.killbill.generators.ClientLibraryBaseGenerator - Generating file for object UsagePriceOverride
[main] INFO com.ning.killbill.generators.ClientLibraryBaseGenerator - Generating file for object VersionedCatalog
Exception in thread "main" com.ning.killbill.generators.GeneratorException: Cannot find classEnumOrInterface Undefined
	at com.ning.killbill.generators.BaseGenerator.findClassEnumOrInterface(BaseGenerator.java:67)
	at com.ning.killbill.generators.ruby.JRubyPluginGenerator.writeConversionToJava(JRubyPluginGenerator.java:688)
	at com.ning.killbill.generators.ruby.JRubyPluginGenerator.writeConversionToJava(JRubyPluginGenerator.java:573)
	at com.ning.killbill.generators.ruby.JRubyPluginGenerator.writeConversionToJava(JRubyPluginGenerator.java:569)
	at com.ning.killbill.generators.ruby.JRubyPluginGenerator.writeConversionToJava(JRubyPluginGenerator.java:661)
	at com.ning.killbill.generators.ruby.JRubyPluginGenerator.writeConversionToJava(JRubyPluginGenerator.java:573)
	at com.ning.killbill.generators.ruby.JRubyPluginGenerator.writeConversionToJava(JRubyPluginGenerator.java:565)
	at com.ning.killbill.generators.ruby.JRubyPluginGenerator.generateToJava(JRubyPluginGenerator.java:531)
	at com.ning.killbill.generators.ruby.JRubyPluginGenerator.generateForPojo(JRubyPluginGenerator.java:357)
	at com.ning.killbill.generators.ruby.JRubyPluginGenerator.generateClass(JRubyPluginGenerator.java:144)
	at com.ning.killbill.generators.ClientLibraryBaseGenerator.generate(ClientLibraryBaseGenerator.java:65)
	at com.ning.killbill.generators.DistpatchGenerator.generate(DistpatchGenerator.java:33)
	at com.ning.killbill.KillbillParser.main(KillbillParser.java:50)
```
